variables:
  length: 1 # default content length, use 1 to measure packets per second
  threads: 512 # number of connections to establish
  duration: 15 # duration in seconds of the benchmark

jobs:
  server:
    source:
      repository: https://github.com/sebastienros/PacketsPerSecond
      project: PacketsPerSecond.csproj
    arguments: "--server --length {{length}} --threads {{threads}}"

  client:
    source:
      repository: https://github.com/sebastienros/PacketsPerSecond
      project: PacketsPerSecond.csproj
    waitForExit: true
    arguments: "--client {{serverAddress}} --threads {{threads}} --length {{length}} --duration {{duration}}"
    options:
      displayOutput: true

scenarios:
  packetspersecond:
    application:
      job: server
      variables: 
        length: 1
    load:
      job: client
      variables: 
        length: 1
